#!/bin/bash
# testscript - v0.1

# base framework for the command line interface

# define our vars
DRYRUN=false                    # dry-run false by default
QUIET=false                     # quiet false by default
USAGE="Usage: `basename $0` [-hnvq]"
VERBOSE=false                   # verbose false by default

# if no arguments are passed, printout usage
if [ $# -eq 0 ]
then
    # TODO - determine correct usage
    echo "$USAGE"
    exit
fi

# getopts gets the short options (the -[char] arguments)
while getopts "hnqv" Opts
do
    case $Opts in
        -h )    
            echo "this is the help flag" ;;
        -n )
            DRYRUN=true ;;
        -q )
            QUIET=true; VERBOSE=false ;;
        -v )
            VERBOSE=true; QUIET=false ;;
        * )     # default case 
            echo "$USAGE"; exit ;;
    esac
done
exit
